version: "3.8"
services:
  mysqldb:

    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:   # Use the same password you set when running the container
      MYSQL_DATABASE: achat_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app_achat:
    depends_on:
      - mysqldb
    image: mariembe/achat:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/achat_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        
      }'
      stdin_open: true
      tty: true
